=== MireilleB/Fichiers-XML-exemples/ma_bibliotheque.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="bibliotheque">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="magazine">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titre" type="xs:string"/>
                            <xs:element name="dateparution" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="roman">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titre" type="xs:string"/>
                            <xs:element name="auteur" type="xs:string"/>
                            <xs:element name="prix" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>
<!-- Je définie que BIBLIOTHEQUE peut contenir au choix (xs:choice) un nombre quelquonque (maxOccurs="unbounded") d'élements ROMAN et MAGAZINE.
Chaque MAGAZINE comprend obligatoirement une séquence (xs:sequence) de deux éléments: un TITRE et une DATEPARUTION.
La DATEPARUTION contient obligatoirement une date (type="xs:date", format année-mois-jour) -->

=== MireilleB/Fichiers-XML-exemples/ma_bibliotheque.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliotheque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ma_bibliotheque.xsd">
	<roman>
		<titre>Imajica</titre>
		<auteur>Clive Barker</auteur>
		<prix>6</prix>
		
	</roman>
	<roman>
		<titre>Dune</titre>
		<auteur>Frank Herbert</auteur>
		<prix>7</prix>
	</roman>
	<magazine>
		<titre>Science et Vie</titre>
		<dateparution>2019-02-01</dateparution>
	</magazine>
	<roman>
		<titre>Christine</titre>
		<auteur>Stephen King</auteur>
		<prix>5</prix>
	</roman>
</bibliotheque>
